# Generated by Django 3.1.7 on 2021-03-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20210312_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='category',
            new_name='name',
        ),
    ]
