# Generated by Django 3.1.7 on 2021-03-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_auto_20210312_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='category',
        ),
    ]
