# Generated by Django 3.1.7 on 2021-03-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_auto_20210313_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='news_img/', upload_to='news_img/'),
        ),
    ]
